### ISSUE TITLE
newton.c example misinterprets pll_compute_likelihood_derivatives return value

### ISSUE THREAD

**Issue by bcclaywell** [xflouris/libpll#116]
The Newton's method branch length optimization example (`newton.c`) appears to misinterpret what `pll_compute_likelihood_derivatives` returns [here](https://github.com/xflouris/libpll/blob/5727e25dc7a54049358b74aae362228646c0f1c3/examples/newton/newton.c#L68). It stores the return value as `double opt_logl` (optimized log-likelihood?) when in fact the function [returns an `int`](https://github.com/xflouris/libpll/blob/5727e25dc7a54049358b74aae362228646c0f1c3/src/derivatives.c#L208) that as far as I can tell is a status code.

**Comment by xflouris** [comment]
thanks @bcclaywell , we forgot to update the example after a recent change in the derivative functions. I'll update the code beginning of next week.

**Comment by xflouris** [comment]
started working on this

**Comment by stamatak** [comment]
can we close this?
