### ISSUE TITLE
Ascertainment bias correction for rooted trees

### ISSUE THREAD

**Issue by xflouris** [xflouris/libpll#124]
Function `root_loglikelihood_asc_bias` should use the extra sites allocated for asc bias correction and not the partition sites.

**Comment by ddarriba** [comment]
Fixed

**Comment by xflouris** [comment]
@ddarriba : can you also fix the asc bias test (asc-bias)?

**Comment by ddarriba** [comment]
It was fixed, but an entry of "*.o" in my .gitignore file prevented the update of the output. I'll push it together with the new test format
