### ISSUE TITLE
Re-entrant cross-platform random number generator

### ISSUE THREAD

**Issue by xflouris** [xflouris/libpll#133]
Implement `random_r` and  and `srandom_r` since MAC does not have these functions. Use  the version from the GNU libc.

**Comment by xflouris** [comment]
Imported code from glibc 2.23 to have the re-entrant pseudo-random number generator functions available for MAC and Windows.

@amkozlov : from now on, use the pll_ prefixed functions (srandom_r,random_r,initstate_r,setstate_r). They have the exact same behaviour as the GNUC calls (imported code).

For an example see [stepwise.c](https://github.com/xflouris/libpll/blob/dev/src/stepwise.c) or the attached example source code, where I use pll_{s}random_r to simulate the non-reentrant random().

**Comment by amkozlov** [comment]
thanks Tomas! Does it mean that libpll now compiles on Mac?

**Comment by xflouris** [comment]
Yes,it compiles fine. There are still some portability issues with the testing framework, but library code and examples work perfectly.

**Comment by amkozlov** [comment]
great, thanks!
