### ISSUE TITLE
derivatives-oddstates segmentation fault

### ISSUE THREAD

**Issue by xflouris** [xflouris/libpll#139]
When compiling libpll with `clang` I get a segmentation fault with the [derivatives-oddstates test case](https://github.com/xflouris/libpll/blob/master/test/src/derivatives-oddstates.c) when using tip-pattern and AVX2. Here's how to reproduce the error:

```bash
cd $LIBPLL_PATH
CC=clang ./configure; make && sudo make install
test/obj/derivatives-oddstates tv avx2
```

Surprisingly, if I use `valgrind test/obj/derivatives-oddstates tv avx2` I often get no error.

Also, using AVX instead of AVX2 works without problems.

**Comment by amkozlov** [comment]
can't reproduce it on Mac with dba4e07f84815313e2c6eaea72af3d2940309596 and

```
apple-sco:test sco$ clang -v
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

have you recompiled the tests as well with `clang`? if so, could you please run it with `gdb` and post the output?

**Comment by xflouris** [comment]
@amkozlov : i didn't try it on mac, only on linux. Tests can be compiled with either gcc or clang, it doesn't matter. I'll check with gdb.

**Comment by amkozlov** [comment]
@xflouris: all tests run successfully with the latest commit on my machine, with both GCC and clang. could you please double-check?

**Comment by xflouris** [comment]
works fine now! closing the issue
