### ISSUE TITLE
use GCC's __builtin_cpu_supports which is nicer than cpuid

### ISSUE THREAD

**Issue by tillea** [xflouris/libpll#141]
Hi,
there seem to be some portability issues when using cpuid.  James Cowgill proposed a [patch](https://anonscm.debian.org/cgit/debian-med/libpll.git/tree/debian/patches/hardware-detect.patch) which enables building libpll for any architecture supported by Debian.  Please consider applying it.
Kind regards, Andreas.

**Comment by xflouris** [comment]
changed to __builtin_cpu_supports, but kept assembly code for gcc version (prior 4.8.0) that did not have builtins, and also for clang (prior 3.8.0).
