### ISSUE TITLE
Relation to libpll.org

### ISSUE THREAD

**Issue by usamec** [xflouris/libpll#144]
Seems like this repo and library at libpll.org serve almost same purpose and are authored by same people, but contain quite different code and API.
It would be nice, if the relationship between these two projects was clarified in documentation.

**Comment by usamec** [comment]
I have found answer in google groups:
"Hello Andreas,

there is a new version of the libpll, which is available here:

https://github.com/xflouris/libpll

The version in the 'dev' branch is the most up-to-date version, and I will update the 'master' branch by the end of the week, or as soon as I finish with some pending issues.

The old PLL library (which might still be used by some programs) does not receive maintenance, and most of new influential software, such as the new RAxML version (which includes it as a sub-module), already use the new libpll.

You can use the issue system on github, and I'm happy to incorporate suggestions that will make libpll a better software. The autotools configuration is also much better, and installation is much easier.

With best regards,
Tomas Flouri"

https://groups.google.com/d/msg/pll-users/74UeGY16Hgw/-DcrTC8xBwAJ

I would be nice to propagate this to relevant places.

**Comment by xflouris** [comment]
Hello @usamec ,
thanks for the suggestion. I will update libpll.org beginning of october to reflect the new library.
