### ISSUE TITLE
Current status of libpll

### ISSUE THREAD

**Issue by andrewyatz** [xflouris/libpll#145]
We just realised today that www.libpll.org is no longer responding and we cannot download the v.1 set of libpll tools. I'm not sure I am aware of the relationship between the library that used to be hosted on www.libpll.org and the releases that's made available from here. Can someone help out and confirm are we okay to switch over to using 0.3.2?

Thanks

**Comment by xflouris** [comment]
Hello @andrewyatz ,
thanks for reporting this. The current version of libpll (0.3.2) on this repository is the latest version and the one that is maintained/developed. The old version that used to be on www.libpll.org is no longer supported nor maintained and is completely different structurally than the version here. I can make it available to you though, in case you need it, but I would not recommend using it anymore.

I plan to update libpll.org accordingly in the next days with the new libpll.

Best regards,
Tomas

**Comment by andrewyatz** [comment]
Hi @xflouris and thanks for the response. This makes a fair bit of sense. It's actually not my group that depends on the v1 libpll but [phyldog](http://pbil.univ-lyon1.fr/software/phyldog/). Their source is available from https://github.com/Boussau/PHYLDOG. 

They have a very specific dependency on 1.0.2. I'm not in a place to comment how easy it is for them to switch to your newer version but making these deprecated releases available would be of huge help to those using phyldog otherwise I'm not sure anyone will be able to use their software. I've raised an issue with their GitHub repo now.

Is there a good way to resolve this from your POV?

Andy

**Comment by xflouris** [comment]
Hi @andrewyatz , thanks for the information. I was not aware of this problem. I have now put back the original www.libpll.org website and the files it pointed to. I will keep all download links intact even after the website is updated the new libpll version, such that no such problems occur in the future. 
Does this solve the problem?

Tomas

**Comment by BenoitMorel** [comment]
Hi @andrewyatz,
Thanks for reporting this.
I am already working with Phyldog's team to integrate the new libpll into Phyldog. It is taking some time but it will solve the issue.
Benoit

**Comment by andrewyatz** [comment]
This is fantastic thank you @xflouris I can now compile libpll 👍 . And thank you @BenoitMorel for looking into integrating the new libpll library. 

Happy to consider the issue closed
